services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb-host
    networks:
      - project_net
    restart: on-failure      
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    build:
      context: ./../../../projects/backend
      dockerfile: Dockerfile.dev
    # env_file: ./../../../projects/backend/.env
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:admin@mongodb-host:27017
      HTTP_PORT: 3000
    volumes:
      - ./../../../projects/backend:/home/node/app
    ports:
      - 3000:3000
    hostname: backend-host
    networks:
      - project_net
    restart: on-failure      
    deploy:
      resources:
        limits:
          memory: 256M

  frontend:
    stdin_open: true
    build:
      context: ./../../../projects/frontend
      dockerfile: Dockerfile.dev
    # env_file: ./../../../projects/frontend/.env.local
    environment:
      NODE_ENV: development
      PORT: 4000
    volumes:
      - ./../../../projects/frontend:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
    ports:
      - "4000:4000"
    hostname: frontend-host
    networks:
      project_net:


volumes:
  mongodb_data:


networks:
  project_net:
